const Joi = require("joi");
const propertySchema = Joi.object({
  Address: Joi.string(),
  PropertyName: Joi.string(),
  Description: Joi.string(),
  Category: Joi.string(),
  SubCategory: Joi.string(),
  PropertyType: Joi.string(),
  PropertySubType: Joi.string(),
  PropertyTypeRadio: Joi.string(),
  beds: Joi.number().min(0),
  baths: Joi.number().min(0),
  reception: Joi.number().min(0),
  tenure: Joi.string(),
  size: Joi.string(),
  price: Joi.string(),
  priceType: Joi.string(),
  minimumAcceptablePrice: Joi.number(),
  selectType: Joi.string(),
  referalFee: Joi.string(),
  image: Joi.array().items(Joi.string()),
  video: Joi.array().items(Joi.string()),
  virtualTourUrl: Joi.string(),
  energyEfficiencyRating: Joi.array().items(Joi.string()),
  floorPlan: Joi.array().items(Joi.string()),
  brochure: Joi.array().items(Joi.string()),
  energyEfficiencyRatingType: Joi.string(),
  brochureType: Joi.string(),
  floorPlanType: Joi.string(),
  miscellaneousType: Joi.string(),
  miscellaneous: Joi.array().items(Joi.string()),
  keyFeature: Joi.array().items(Joi.string()),
  tags: Joi.array().items(Joi.string()),
  planType: Joi.string(),
  authId: Joi.string(),
  lat: Joi.number(),
  lng: Joi.number(),
  createdAt: Joi.string(),
  updatedAt: Joi.string(),
});
const requirementsSchema = Joi.object({
  category: Joi.string().required(),
  location: Joi.string().allow("").optional(),
  lat: Joi.number().required(),
  lng: Joi.number().required(),
  radius: Joi.string().allow("").optional(),
  propertyType: Joi.string().required(),
  propertySubType: Joi.string().required(),
  size: Joi.string().required(),
  addedToSite: Joi.string().allow("").optional(),
  soldType: Joi.string().allow("").optional(),
  minPriceRange: Joi.string().required(),
  maxPriceRange: Joi.string().required(),
  clientName: Joi.string().required(),
  clientEmail: Joi.string().required(),
  keyFeature: Joi.array().items(Joi.string()).required(),
  tags: Joi.array().items(Joi.string()).required(),
  Location: Joi.string().required(),
  Radius: Joi.string().required(),
  authId: Joi.string().required(),
  createdAt: Joi.string().required(),
});
const offersSchema = Joi.object({
  notes: Joi.string().allow("").optional(),
  price: Joi.number().required(),
  authId: Joi.string().required(),
  agentAuthId: Joi.string().required(),
  propertyId: Joi.string().required(),
});
const viewingsSchema = Joi.object({
  date: Joi.date().iso().required(),
  slot: Joi.string().required(),
  notes: Joi.string().allow("").optional(),
  authId: Joi.string().required(),
  agentAuthId: Joi.string().required(),
  propertyId: Joi.string().required(),
  status: Joi.string().required(),
});
const notificationSchema = Joi.object({
  authId: Joi.string().required(),
  message: Joi.string().required(),
  type: Joi.string().required(),
  createdAt: Joi.string().required(),
  isRead: Joi.boolean().required(),
  propertyId: Joi.string().required(),
  agentAuthId: Joi.string().required(),
});
module.exports = {
  propertySchema,
  requirementsSchema,
  offersSchema,
  viewingsSchema,
  notificationSchema,
};
